package chainstore

import (
	"context"
	"crypto/sha256"

	"github.com/google/uuid"
)

// NodeID is a 20-byte opaque node identifier computed by Charon.
// NodeID = first 20 bytes of sha256(tenantKey + "\x00" + responseID).
// Callers never construct NodeIDs directly — all public Store methods accept
// string response IDs and an optional tenant key.
type NodeID [20]byte

// nodeID derives a NodeID from an external response ID and tenant key.
// sha256 used for namespace derivation — collision resistance required; not a MAC.
// tenantKey may be empty for single-tenant deployments.
func nodeID(tenantKey, responseID string) NodeID {
	h := sha256.Sum256([]byte(tenantKey + "\x00" + responseID))
	var id NodeID
	copy(id[:], h[:])
	return id
}

// BucketID identifies an LRU time bucket: BucketID = UnixSeconds / BucketDuration.
type BucketID uint64

// BlobID is a 16-byte UUID identifying a blob.
// A Node holds BlobIDs as pointers so the blob bytes never need to move during bucket promotions.
type BlobID [16]byte

// Node is the backend metadata record for one conversation turn.
// Encoding (binary layout, key prefixes) is entirely backend-internal.
type Node struct {
	Version          uint8
	ID               NodeID
	ParentID         NodeID   // zero value = root node
	RequestBlobID    BlobID   // UUID → request (input) blob; zero until request is stored
	ResponseBlobID   BlobID   // UUID → response (output) blob; zero until turn is completed
	LastAccessUnix   int64    // Unix seconds; updated on access
	CreatedAt        int64    // Unix seconds; set at store time, never updated
	BucketID         BucketID // bucket at last promotion; ground truth for eviction order
	RequestBlobSize  uint32
	ResponseBlobSize uint32
	Depth            uint32 // 0 = root; enables slice preallocation in LoadChain
	Status           uint8  // NodeStatusCompleted or NodeStatusFailed
	ResponseID       string // external caller-supplied ID; stored verbatim, max 255 bytes
}

// Node status constants.
const (
	NodeStatusCompleted uint8 = iota
	NodeStatusFailed
)

// BlobEntry carries a blob's ID and raw bytes in a Transaction.
type BlobEntry struct {
	BlobID BlobID
	Data   []byte
}

// BucketMove records a bucket-index promotion for one node.
// OldBucket is required: the pebble LRU key encodes bucket+nodeID, so the old key
// must be deleted by its full key — the backend cannot derive it without a read.
type BucketMove struct {
	NodeID    NodeID
	OldBucket BucketID
	NewBucket BucketID
}

// ChildEntry declares a parent→child relationship to be recorded in the backend.
// Required so the TTL reaper can walk subtrees via GetChildren.
type ChildEntry struct {
	Parent NodeID
	Child  NodeID
}

// StatsDelta carries atomic counter adjustments for a Transaction.
// Applied together with the KV mutations so counts stay consistent across restarts.
type StatsDelta struct {
	EntryDelta int64
	BytesDelta int64
}

// StagingEntry pairs a staging key with the partial Node it holds.
// The staging key is a BlobID-width UUID generated by ResolveAndStage.
// Staging records are stored under pfxStaging and are invisible to chain walks.
type StagingEntry struct {
	StagingID BlobID
	Node      Node
}

// Transaction describes what to change, not how.
// Each backend translates it to its native atomic primitive.
// OpID makes commits idempotent — backends that support retries use it to detect
// duplicate deliveries; local backends (Pebble) ignore it.
//
// Intended combinations:
//   - Store a turn:    PutNodes + PutBlobs (request blob) + PutChildren + StatsDelta
//   - Complete a turn: PutNodes + PutBlobs (response blob) + StatsDelta
//   - Touch/promote:   PutNodes (LastAccessUnix) + BucketMoves
//   - Delete:          DeleteNodes + DeleteBlobs + DeleteChildren + StatsDelta
//   - Stage a request: PutStagingNodes + PutBlobs (request blob)
//   - Commit staged:   PutNodes + PutBlobs (response blob) + PutChildren + DeleteStagingNodes + StatsDelta
type Transaction struct {
	OpID uuid.UUID

	PutNodes    []Node
	DeleteNodes []NodeID

	PutBlobs    []BlobEntry
	DeleteBlobs []BlobID

	PutChildren    []ChildEntry
	DeleteChildren []ChildEntry

	BucketMoves []BucketMove

	// Staging record operations; invisible to chain walks and eviction scans.
	PutStagingNodes    []StagingEntry
	DeleteStagingNodes []BlobID // staging IDs only; blobs go in DeleteBlobs

	StatsDelta StatsDelta
}

// Backend is the only interface the business logic sees.
// Each implementation maps these domain operations to its native storage primitives.
// No key encodings, batch primitives, or scan APIs appear above this boundary.
type Backend interface {
	// LoadChain walks from leaf to root and returns nodes leaf-first.
	// Returns ErrNotFound if leaf is absent; ErrChainExpired if an ancestor was
	// capacity-evicted; ErrChainCorrupted if a parent pointer dangles unexpectedly.
	LoadChain(ctx context.Context, leaf NodeID) ([]Node, error)

	// GetNode fetches a single node's metadata. ErrNotFound if absent.
	GetNode(ctx context.Context, id NodeID) (Node, error)

	// GetBlobs fetches both blobs for a node in one call.
	// Either blob may be nil if its BlobID is zero (not yet stored).
	// Returns (requestBlob, responseBlob, err).
	GetBlobs(ctx context.Context, node Node) ([]byte, []byte, error)

	// Commit atomically applies all mutations in tx.
	// OpID makes commits idempotent — safe to retry on transient failures.
	Commit(ctx context.Context, tx Transaction) error

	// GetEvictionCandidates returns up to limit node IDs from the given bucket.
	GetEvictionCandidates(ctx context.Context, bucket BucketID, limit int) ([]NodeID, error)

	// OldestBucket returns the BucketID of the oldest non-empty bucket,
	// or ErrNotFound if the store is empty.
	OldestBucket(ctx context.Context) (BucketID, error)

	// GetChildren returns the direct children of parentID.
	GetChildren(ctx context.Context, parentID NodeID) ([]NodeID, error)

	// GetStagingNode fetches the partial Node stored under a staging key.
	// Returns ErrUnknownStaging if the staging record is absent.
	GetStagingNode(ctx context.Context, stagingID BlobID) (Node, error)

	// ListStagingOlderThan returns all staging entries whose Node.CreatedAt
	// is less than cutoffUnixSecs. Used by the staging TTL reaper to clean
	// orphaned records left by a proxy crash between ResolveAndStage and StoreWithStaging.
	ListStagingOlderThan(ctx context.Context, cutoffUnixSecs int64) ([]StagingEntry, error)

	// Stats returns current entry count and total blob bytes.
	Stats(ctx context.Context) (entries int64, bytes int64, err error)

	// Close releases all resources.
	Close() error
}
